---
- name: Install Docker and Starting app
  hosts: prod
  become: yes  
  
  tasks:
  - name: Update and upgrade apt packages
    apt:
      update_cache: yes
      cache_valid_time: 86400 
  
  - name: Install Docker
    apt: name=docker.io state=latest

  - name: Add user to docker group
    command: "sudo gpasswd -a $USER docker"
    
  - name: Ensure python3-docker package is installed
    apt:
        name: python3-docker
        state: present
        update_cache: True

  - name: Get a list of all running containers
    docker_host_info:
        containers: True
    register: docker_info
  - name: Stop all running containers
    docker_container:
        name: '{{ item.Names[0] | regex_replace("^/", "") }}'
        state: stopped
    loop: '{{ docker_info.containers }}'

  - name: Start a container
    command: "docker run -d --rm -p 8080:8080 kiykomi/pet-clinic:latest"

  
